### ISSUE TITLE
Cannot search todo Item / cannot see all items

### ISSUE THREAD

**Issue by unmeshvrije** [hanbingli/to-do-list#3]
After I create the todo-item, the main page is empty.
I don't see my todo-item.

It is not easy to find it. 

Also after logging in, the user does not know where to click and why.

**Comment by hanbingli** [comment]
Yes that's my current problem, to see everything after a submit, you need to refresh the page. I didn't figure out how to re-render the page on dependency.

**Comment by hanbingli** [comment]
list rendering after login fixed
